name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl
    
    - name: Install BATS
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        ./install.sh /usr/local
        cd ..
        rm -rf bats-core
    
    - name: Run BATS tests
      run: |
        bats --tap tests/unit/*.bats
      continue-on-error: true
    
    - name: Check test results
      if: always()
      run: |
        if [ $? -ne 0 ]; then
          echo "::error::BATS tests failed"
          exit 1
        fi

  test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Pester
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -SkipPublisherCheck
    
    - name: Run Pester tests
      shell: pwsh
      run: |
        $result = Invoke-Pester tests/unit/*.Tests.ps1 -Output Detailed -PassThru
        if ($result.FailedCount -gt 0) {
          Write-Error "Pester tests failed"
          exit 1
        }
      continue-on-error: true
    
    - name: Check test results
      if: always()
      shell: pwsh
      run: |
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Pester tests failed"
          exit 1
        } 